var srctexts = [
'1', 'a',
'In der Nähe der Leucht-Heultonne Humber 5 wurde ein gekentertes Rettungsfloß beobachtet. Überlebende wurden nicht gesichtet. Schiffe in dem Gebiet werden gebeten, scharf Ausschau zu halten.', 
'In vicinity of light and whistle buoy Humber 5 capsized life raft observed. Survivors were not sighted. Ships in area are requested to keep sharp lookout.', 
'2', 'b',
'Seydisfjord/DFBY auf Position 61-10N 003-45E, nach einer Explosion Feuer im Motorraum, zwei Personen schwer verletzt, wir müssen das Schiff verlassen, benötigen sofortige Hilfe.',
'Seydisfjord/DFBY in position 61-10N 003-45E, after explosion fire in engine room, two persons are seriously injured, we have to abandon the vessel, require immediate help.',
'3', 'b',
'M/S Freyburg/DCAW berichtet Mensch über Bord, um 0730 UTC zuletzt gesichtet auf Position 53-53N 008-56E. Alle Schiffe in der Nähe werden gebeten, scharf Ausschau zu halten und die Seenotleitung Bremen zu informieren.',
'M/V Freyburg/DCAW reports person over board, last seen in position 53-53N 008- 56E at 0730 UTC. All ships in vicinity are requested to keep sharp lookout and report to Maritime Rescue Co-ordination Centre Bremen.',
'4', 'b',
'Vikingbank/DESI auf Position 54-07N 008-46E, Ruder gebrochen, treiben in rauer See auf die Sände zu, benötigen sofortige Hilfe.',
'Vikingbank/DESI in position 54-07N 008-46E, rudder broken, drifting in rough sea towards the banks, require immediate assistance.',
'5', 'a',
'Mensch über Bord auf Position 54-12N 012-03E um 2110 UTC. Schiffe in der Nähe werden gebeten, scharf Ausschau zu halten und der Seenotleitung Bremen zu berichten.',
'Person over board in position 54-12N 012-03E at 2110 UTC. Ships in vicinity are requested to keep sharp lookout and to report to Maritime Rescue Co-ordination Centre Bremen.',
'6', 'b',
'M/S Kybfels/DEJM auf Position 48-28N 005-14W, habe starke Schlagseite nach Backbord. Schiffe in der Nähe bitte Position, Kurs und Geschwindigkeit für mögliche Hilfeleistung angeben.',
'M/V Kybfels/DEJM in position 48-28N 005-14W, heavy list to port side. Ships in vicinity please indicate position, course and speed for possible assistance.',
'7', 'a',
'Rote Raketen beobachtet auf Position 55-16N 016-23E, rechtweisende Peilung 45 Grad, alle Schiffe in diesem Gebiet bitte scharf Ausschau halten und an MRCC Göteborg berichten.',
'Red rockets observed in position 55-16N 016-23E, true bearing of 45 degrees, all ships in this area please keep sharp lookout and report to MRCC Gothenburg.',
'8', 'a',
'Sturmwarnung für Skagerrak und Kattegat, West 8 bis 9, abnehmend 7, raue See, Schauer, mäßige bis schlechte Sicht.',
'Gale warning for Skagerrak and Kattegat, west force 8 to 9, decreasing to force 7, rough sea, showers, moderate to poor visibility.',
'9', 'b',
'M/S Gutenfels/DEEV auf Position 16-28S 174-51E, Wassereinbruch, Schiff befindet sich im kritischen Zustand, Schiffe in dem Gebiet werden gebeten, diese Position anzusteuern, um Hilfe zu leisten.',
'M/V Gutenfels/DEEV in position 16-28S 174-51E, flooding, ship is in critical condition, ships in area are requested to approach to this position for assistance.',
'10', 'a',
'Um 0732 UTC folgendes auf UKW-Kanal 16 empfangen: "MAYDAY Fjaellfjord/ LGBX auf Position 54-14N 007-52E, Explosionen im Maschinenraum, 6 Personen verletzt, benötigen Hubschrauber und medizinische Hilfe".',
'Following received at 0732 UTC on VHF channel 16: "MAYDAY Fjaellfjord/LGBX in position 54-14N 007-52E, explosion in engine room, 6 persons are injured, require helicopter and medical assistance".', 
'11', 'b',
'M/S Undine/DCBY auf Position 54-32N 012-56E, Feuer in den Aufbauten, Schiffe in dem Gebiet werden gebeten, Hilfe bei der Brandabwehr zu leisten.',
'M/V Undine/DCBY in position 54-32N 012-56E, fire in superstructures, vessels in area are requested to assist in fire fighting.',
'12', 'b',
'M/S Hanseatic/DABR auf Position 51-10N 003-45E, Schiff ist wegen defekter Ruderanlage manövrierunfähig, benötige Schlepperhilfe.',
'M/V Hanseatic/DABR in position 51-10N 003-45E, due to defective steering gear vessel is not under command, require tug assistance.',
'13', 'b',
'Yacht Spiekeroog/DB8434 auf Position 12 sm südlich Kap Spartivento ist ein Besatzungsmitglied vom Mast gefallen und schwer verletzt, benötigen dringend ärztliche Hilfe, rechtweisender Kurs 275 Grad, Geschwindigkeit 13 Knoten.',
'Yacht Spiekeroog/DB8434 in position 12 nm south of Cape Spartivento, a crew member has fallen off the mast and is seriously injured, require urgent medical assistance, true course 275 degrees, speed 13 knots.',
'14', 'b',
'Segelyacht Hadriane/DD2663 auf Position 54-38N 011-13E, Kollision mit Fischereifahrzeug Meyenburg/DCYJ, Yacht sinkt nach Wassereinbruch, benötigen sofortige Hilfe.',
'S/Y Hadriane/DD2663 in position 54-38N 011-13E, in collision with fishing vessel Meyenburg/DCYJ, yacht is sinking after flooding, require immediate assistance.',
'15', 'a',
'Segelboot Rubin/OZMO, 12 m Länge, roter Rumpf und weiße Segel, zwei Personen an Bord, verließ Klintholm am 16. Juli um 0600 Ortszeit mit Bestimmungshafen Visby, ist bisher dort nicht eingetroffen, die Schifffahrt wird gebeten, scharf Ausschau zu halten und an Lyngby Radio zu berichten.',
'Sailing boat Rubin/OZMO, length 12 m, red hull and white sails, two persons on board, left Klintholm on July 16th at 0600 local time, bound for Visby and has not yet arrived there, shipping is requested to keep sharp lookout and to report to Lyngby Radio.',
'16', 'b',
'Tazacorte/DCAX auf Position 53-54N 008-47E, Schiff brennt, Feuer nicht unter Kontrolle, benötige sofortige Hilfe.',
'Tazacorte/DCAX in position 53-54N 008-47E, vessel on fire, fire not under control, require immediate assistance.', 
'17', 'b',
'M/S Tete Oldendorff/DKOV auf Position 55-12N 005-08E, ein Besatzungsmitglied, 56 Jahre alt, ist bewusstlos, Verdacht auf Herzinfarkt, benötige dringend medizinische Hilfe per Hubschrauber.',
'M/V Tete Oldendorff/DKOV in position 55-12N 005-08E, a crew member, 56 years old, is unconscious, suspect of heart attack, require urgently medical assistance by helicopter.',
'18', 'b',
'M/S Atlantica/DEAQ auf Position 55-23N 006-18E, Schiff treibt wegen Maschinenausfall manövrierunfähig in sehr schwerer See und hoher Dünung, benötigen dringend Schlepperhilfe.',
'M/V Atlantica/DEAQ in position 55-23N 006-18E, due to engine trouble ship is not under command and drifting in very rough sea and high swell, require immediate tug assistance.',
'19', 'a',
'Segeljacht Relaxe/SWLU, Beschreibung: Länge 40 Fuß, weißer Rumpf und weiße Aufbauten, braune Segel, unterwegs von Martinique zu den Azoren, seit dem 16. Januar überfällig, Schiffe, die sich auf dieser Route befinden, werden gebeten, scharf Ausschau zu halten und der US Küstenwache zu berichten.',
'Sailing yacht Relaxe/SWLU description: length 40 feet, white hull and white superstructure, brown sails underway from Martinique to the Azores overdue since January 16th, ships on this route are requested to keep sharp lookout and to report to US Coast Guard.',
'20', 'b',
'Segeljacht Acatenanco/DB2932, auf Position 61-17N 004-28E, gebrochener Mast, Ruderschaden, Schiff treibt manövrierunfähig in schwerer See, benötigen Schlepperhilfe.',
'Sailing yacht Acatenanco/DB2932 in position 61-17N 004-28E, broken mast, damaged rudder, vessel is not under command, drifting in rough sea, require tug assistance.',
'21', 'a',
'Im Vorhersagegebiet Dogger Bank starke westliche Winde zunehmend auf Sturmstärke 8 bis 9, später rechtdrehend, zeitweise Sprühregen, mäßige bis  schlechte Sicht.',
'Forecast area Dogger Bank strong westerly winds increasing to gale force 8 to 9, veering later, drizzle at times, moderate to poor visibility.',
'22', 'a',
'Auf der Position 43-00N 009-19W sind mehrere rot gestrichene 40-Fuß-Container gesichtet worden, ein Container mit der Aufschrift TEXASCON, Schiffe in diesem Gebiet werden gebeten, vorsichtig zu navigieren.',
'In position 43-00N 009-19W observed several drifting 40-feet containers, red painted, one container marked with TEXASCON, ships in this area are requested to navigate carefully.',
'23', 'b',
'M/S Xanthippe hat auf Position 51-28N 002-40E Anker verloren. Schiffe in dem Gebiet werden gebeten, dort weder zu ankern noch Fischereigeschirr zu nutzen.',
'M/V Xanthippe in position 51-28N 002-40E has lost anchor. Shipping in this area is requested neither to anchor nor to use fishing gear.',
'24', 'a',
'Fahrwasser zwischen Den Helder und Den Oever, die Leucht-Heultonne MG 18 ist als verlöscht gemeldet. Die Schifffahrt in diesem Gebiet wird gebeten, vorsichtig zu navigieren.',
'Fairway between Den Helder and Den Oever light and whistle buoy MG 18 is reported unlit. Shipping in this area is requested to navigate with caution.',
'25', 'a',
'Wettervorhersage für das Gebiet nördlich von Portugal: Regen oder Schauer, zeitweise Südwest 6, rasch zunehmend auf West 8, später rechtdrehend auf Nordwest Stärke 5.',
'Weather forecast for the area north of Portugal: rain or showers, at times southwest force 6 rapidly increasing to west force 8, veering to northwest force 5 later.',
'26', 'a',
'Unterwasser-Kabelarbeiten werden bis zum 16. Februar durch M/S Leon Thevesin fortgeführt. Die Schifffahrt wird gebeten, mehr als 2 sm Abstand von der Position 33- 55N 008-04W zu halten.',
'Underwater cable operations in progress until February 16th by M/V Leon Thevesin. Shipping is requested to keep a berth of more than 2 nm of position 33-55N 008-04W.',
'27', 'a',
'Nautische Warnung. Westliche Ostsee. Verkehrstrennungsgebiet südlich Gedser. Austausch der Betonnung des Tieffahrwasserwegs und des Verkehrstrennungsgebietes wird laut Nachrichten für Seefahrer 41/01 vom 28. Mai bis 03. Juni durchgeführt werden.',
'Navigational warning. Western Baltic (Sea): Traffic separation scheme south of Gedser. Replacement of buoyage of deep water lane and traffic separation scheme will be carried out from 28 May to 03 June according to German notices to mariners 41/01.',
];
